version: "3"
services:

    movies-api:
        image: 'geekshubsdevops/movies-api:latest'
        container_name: 'movies-api'
        ports:
            - "3000:3000"
        environment: 
            MONGO_URL: 'mongo'
            MONGO_DATABASE: 'movies'

    mongo:
        container_name: mongo
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ../../data/db:/data/db

    master:
        image: locustio/locust
        working_dir: /locust
        ports:
            - "8089:8089"
        volumes:
            - ../../source/locust/benchmarks:/locust
        command: -f /locust/locustfile.py --master -H http://master:8089
  
    worker:
        image: locustio/locust
        volumes:
        - ../../source/locust/benchmarks:/locust
        command: -f /locust/locustfile.py --worker --master-host master


    worker2:
        image: locustio/locust
        volumes:
        - ../../source/locust/benchmarks:/locust
        command: -f /locust/locustfile.py --worker --master-host master        